title: Stacy Brody
position: Medical Librarian
email: 
keywords: medical librarianship, scholarly communications, systematic reviews, literature searching 
google_scholar: https://scholar.google.com/citations?user=e-V_fzQAAAAJ&hl=en
orcid_id: https://orcid.org/0000-0002-2817-3849
description: Academic website for Stacy Brody, Medical Librarian, Washington, D.C. 
canonical: https://sbbrody.github.io
remote_theme: yaoyao-liu/minimal-light
