title: Stacy Brody
description: Medical Librarian
google_scholar: https://scholar.google.com/citations?user=e-V_fzQAAAAJ&hl=en
linkedin: https://www.linkedin.com/in/stacybbrody/
ordid_id: https://orcid.org/0000-0002-2817-3849
remote_theme: yaoyao-liu/minimal-light
